### ISSUE TITLE
Can't build TesseractOCRPlugin 

### ISSUE THREAD

**Issue by oumahti** [JakeTrans/TesseractOCRPlugin#15]
i can not build the solution. 
![TesseractOCRPlugin](https://user-images.githubusercontent.com/57234756/108235585-3e314d80-7146-11eb-90cb-fe0edc92a15d.png)

**Comment by JakeTrans** [comment]
Hi,

I assume this is based on the master branch, odd for it to fail on those types, what framework version are you building this against? it defaults to 4.6 at the moment

Thanks

Jake

**Comment by oumahti** [comment]
Thanks for your reply.
i tried version 4.6, 4.7.1, 4.7.2

**Comment by JakeTrans** [comment]
Unfortantly I'm not able to get the same error however those out overloads aren't manadatory for the function of the Library.

I've created a new branch here - https://github.com/JakeTrans/TesseractOCRPlugin/tree/Issue-15

I've removed the outs and will later replace them with a results Class, however hopefully this will now build for you

**Comment by JakeTrans** [comment]
master now updated to use TesseractOCRResult rather than out statements.

Probably should have done this before

**Comment by JakeTrans** [comment]
Closing as update made.
